[package]
name = "rasn-cms"
version.workspace = true
edition.workspace = true
description = "Data types for handling Cryptographic Message Syntax."
license.workspace = true
repository.workspace = true

[dependencies.rasn]
version = "0.22"
path = "../.."

[dependencies.rasn-pkix]
version = "0.22"
path = "../pkix"

[dev-dependencies]
pretty_assertions = "1.4.1"
