[package]
name = "rasn-its"
description = "rasn implementations of Intelligent Transport Systems (ITS) ASN.1 specifications for vehicle-to-everything (V2X) communications."
edition.workspace = true
license.workspace = true
version.workspace = true
repository.workspace = true

[dependencies]
bon = { version = "3.1.1", default-features = false }
rasn = { version = "0.22", path = "../.." }

[dev-dependencies]
pretty_assertions = "1.4.1"
